language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - python bootstrap.py -c buildout.cfg
  - bin/buildout annotate
  - bin/buildout -N -q
script: bin/test
after_failure:
  - bin/buildout annotate
