[tox]
envlist =
    py310,py311,py312,py313,py314


[testenv]
usedevelop = true
deps =
    zope.testing
    zc.buildout
    manuel
    zope.testrunner
commands =
    zope-testrunner --path=. --test-path=. --auto-color --auto-progress
